import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const M = require('../nameplate-changes.js');
const Mach = require('../mach-contract.js');
const person = (id, name = '가상 동명인') => ({ participantId: id, name, organization: '가상 기관', position: '담당', status: 'attending', seatId: '', replacesParticipantId: '' });
const packet = (participants, revision = 1, transferId = `transfer-${revision}`) => Mach.createTransfer({ kind: 'roster', eventId: 'synthetic-event', eventName: '가상 검증 행사', revision, baseRevision: 0, transferId, participants });
const project = () => ({ people: [], customLogos: [], design: { defaultLeftLogo: 'hanyang', footerLogo: 'hanyang', templateStyle: 'basic', rotateBack: true, titleSeparator: ' ', nameSize: 78, showPageLabel: false, settingsLocked: false }, selectedIndex: 0, mach: M.metadata(null, 'standalone-event') });
function add(p, people, revision = 1, id) { return M.apply(p, packet(people, revision, id), Object.fromEntries(people.map(x => [x.participantId, { selected: true }]))); }
const render = (p, id) => M.renderValue(p, p.people.find(x => x.id === id));
function printed(p, ids = p.people.map(p => p.id), jobId = 'job-1', time = '2026-01-01T00:00:00Z') { const next = M.clone(p); next.mach.printJobs.push(M.createJob(next, ids.map(id => ({ participantId: id, render: render(p,id), html:'<div>synthetic</div>' })), jobId, time)); return M.complete(next, jobId, time); }

test('stable IDs keep homonyms separate; repeated apply is idempotent', () => { const p = add(project(), [person('p1'), person('p2')]); assert.equal(p.people.length,2); const next = add(p,[person('p1'),person('p2')]); assert.deepEqual(next,p); assert.equal(M.review(p,packet([person('p1'),person('p2')])).length,0); });
test('partial input omissions and unselected rows preserve all other participants', () => { const p = add(project(),[person('p1'),person('p2')]); const changed = packet([{...person('p1'),position:'새 담당'},person('p3')],2); const next = M.apply(p,changed,{p1:{selected:true},p3:{selected:false}}); assert.equal(next.people[0].position,'새 담당'); assert.equal(next.people[1].id,'p2'); assert.equal(next.people.length,2); assert.deepEqual(next.mach.applied[changed.transferId].pendingIds,['p3']); const resumed=M.apply(next,changed,{p3:{selected:true}}); assert.equal(resumed.people.length,3); assert.deepEqual(resumed.mach.applied[changed.transferId].selectedIds,['p1','p3']); });
test('source title correction detects display override and requires explicit resolution', () => { const p=add(project(),[person('p1')]); p.people[0].position='개별 표시'; const incoming=packet([{...person('p1'),position:'새 직책'}],2); const row=M.review(p,incoming)[0]; assert.deepEqual(row.conflicts,['position']); assert.throws(()=>M.apply(p,incoming,{p1:{selected:true}}),/충돌/); const keep=M.apply(p,incoming,{p1:{selected:true,fields:{position:{mode:'local'}}}}); assert.equal(keep.people[0].position,'개별 표시'); const manual=M.apply(p,incoming,{p1:{selected:true,fields:{position:{mode:'manual',value:'확인한 표시'}}}}); assert.equal(manual.people[0].position,'확인한 표시'); assert.equal(p.people[0].position,'개별 표시'); });
test('unchanged source fields retain local line breaks and per-person logo',()=>{const p=add(project(),[person('p1')]);p.people[0].organization='가상\n기관';p.people[0].logoKey='none';const next=add(p,[{...person('p1'),position:'새 직책'}],2);assert.equal(next.people[0].organization,'가상\n기관');assert.equal(next.people[0].logoKey,'none');assert.deepEqual(next.design,p.design);});
test('typo keeps identity while replacement is a separate ID and recall',()=>{let p=printed(add(project(),[person('p1')]));p=add(p,[{...person('p1'),name:'가상 이름 정정'}],2);assert.equal(p.people[0].id,'p1');p=add(p,[{...person('p1'),name:'가상 이름 정정',status:'replaced'},{...person('p2'),replacesParticipantId:'p1'}],3);assert.equal(p.people.length,2);assert.equal(p.mach.recalls.p1.status,'pending');assert.equal(p.people[1].replacesParticipantId,'p1');assert.equal(M.active(p.people[0]),false);});
test('cross-event and stale revision are rejected without mutation',()=>{const p=add(project(),[person('p1')],4);const original=JSON.stringify(p);assert.throws(()=>M.review(p,{...packet([person('p1')],5),eventId:'another'}),/다른 행사/);assert.throws(()=>M.review(p,packet([person('p1')],3)),/오래된/);assert.equal(JSON.stringify(p),original);});
test('legacy is unknown while a newly linked participant needs new printing',()=>{const p=project();p.people.push({id:'legacy',name:'가상 기존',organization:'',position:'',logoKey:'none'});assert.equal(M.status(p,p.people[0],render(p,'legacy')),'출력 여부 미확인');const next=add(p,[person('p1')]);assert.equal(M.status(next,next.people[1],render(next,'p1')),'신규 출력 필요');});
test('seat, note and sorting changes do not trigger reprint',()=>{const p=printed(add(project(),[person('p1'),person('p2')]));const next=M.clone(p);next.people.reverse();next.people[1].seatId='MAIN-L-12';next.people[1].note='인쇄 무관 메모';assert.equal(M.status(next,next.people[1],render(next,'p1')),'변경 없음');});
test('actual visible text, template, font, dimensions, logo and custom image changes trigger reprint',()=>{const p=printed(add(project(),[person('p1')]));for(const [key,value] of [['templateStyle','gold'],['nameSize',50],['plateWidth',200],['footerLogo','erica'],['defaultLeftLogo','none']]){const next=M.clone(p);next.design[key]=value;assert.equal(M.status(next,next.people[0],render(next,'p1')),'수정 재출력 필요',key);}const next=M.clone(p);next.people[0].position='새 표시';assert.equal(M.status(next,next.people[0],render(next,'p1')),'수정 재출력 필요');next.people[0].logoKey='custom-a';next.customLogos=[{id:'custom-a',name:'가상',dataUrl:'data:image/png;base64,AAAA'}];assert.equal(M.status(next,next.people[0],render(next,'p1')),'수정 재출력 필요');});
test('preview-only and editor settings do not trigger reprint',()=>{const p=printed(add(project(),[person('p1')]));const next=M.clone(p);Object.assign(next.design,{showPageLabel:true,settingsLocked:true,autoScaleElements:true,platePreset:'custom'});assert.equal(M.status(next,next.people[0],render(next,'p1')),'변경 없음');});
test('unselected and absent participants never enter selective print job',()=>{let p=add(project(),[person('p1'),person('p2')]);p.people[1].status='absent';const entries=p.people.filter(M.active).map(p1=>({participantId:p1.id,render:render(p,p1.id)}));const job=M.createJob(p,entries,'partial','2026-01-01');assert.deepEqual(job.entries.map(e=>e.participantId),['p1']);assert.equal(p.mach.printJobs.length,0);});
test('late completion confirms immutable job snapshot, never changed latest name',()=>{const p=add(project(),[person('p1')]);const job=M.createJob(p,[{participantId:'p1',render:render(p,'p1')}],'frozen','2026-01-01');p.mach.printJobs.push(job);p.people[0].name='작업 생성 뒤 수정';const next=M.complete(p,'frozen','2026-01-02');assert.equal(next.mach.confirmed.p1.render.name,'가상 동명인');assert.equal(M.status(next,next.people[0],render(next,'p1')),'수정 재출력 필요');assert.equal(p.mach.printJobs[0].status,'unconfirmed');});
test('confirming an older print job cannot overwrite a newer confirmed physical snapshot',()=>{let p=printed(add(project(),[person('p1')]),['p1'],'new','2026-02-01');p.mach.printJobs.push(M.createJob(p,[{participantId:'p1',render:{name:'older'}}],'old','2026-01-01'));p=M.complete(p,'old','2026-03-01');assert.equal(p.mach.confirmed.p1.jobId,'new');});
test('absence after job creation still creates recall when that old job is confirmed',()=>{let p=add(project(),[person('p1')]);p.mach.printJobs.push(M.createJob(p,[{participantId:'p1',render:render(p,'p1')}],'job','2026-01-01'));p=add(p,[{...person('p1'),status:'absent'}],2);p=M.complete(p,'job','2026-01-03');assert.equal(p.mach.recalls.p1.status,'pending');});
test('file roundtrip retains IDs, common design, personal edits, baseline, print jobs and recall',()=>{let p=printed(add(project(),[person('p1'),person('p2')]));p.people[1].organization='별도\n표시';p=add(p,[{...person('p1'),status:'absent'}],2);p.mach.recalls.p1.status='collected';const restored=JSON.parse(JSON.stringify(p));M.validateProject(restored);restored.mach=M.metadata(restored.mach,'ignored');assert.deepEqual(restored,p);});
test('unsafe logos, duplicate IDs, prototype keys and future schema reject',()=>{const p=project();assert.throws(()=>M.validateProject({...p,customLogos:[{dataUrl:'https://external.invalid/track'}]}),/로고/);assert.throws(()=>M.validateProject({...p,people:[{id:'same'},{id:'same'}]}),/중복/);assert.throws(()=>M.validateProject(JSON.parse(JSON.stringify(p).replace('"design":{','"design":{"__proto__":{},'))),/구조/);assert.throws(()=>M.metadata({...p.mach,schemaVersion:999}),/지원하지/);});
test('storage main write failure leaves project and in-memory original unchanged',()=>{const p=project(),old=JSON.stringify(p),map=new Map([['project',old]]);const storage={getItem:k=>map.get(k)||null,setItem(k,v){if(k==='project')throw Error('quota');map.set(k,v)}};const next=add(p,[person('p1')]);assert.throws(()=>Mach.atomicSave(storage,'project',old,next));assert.equal(map.get('project'),old);assert.equal(p.people.length,0);assert.equal(map.get('project:before-mach'),old);});
test('kept local or divergent manual text remains pending rather than acknowledged applied',()=>{const p=add(project(),[person('p1')]);p.people[0].position='별도 표시';const transfer=packet([{...person('p1'),position:'새 원본'}],2);for(const resolution of [{mode:'local'},{mode:'manual',value:'직접 수정'}]){const next=M.apply(p,transfer,{p1:{selected:true,fields:{position:resolution}}});assert.deepEqual(next.mach.applied[transfer.transferId].selectedIds,[]);assert.deepEqual(next.mach.applied[transfer.transferId].pendingIds,['p1']);assert.equal(M.review(next,transfer).length,1);}});
test('identical fresh transfer stores durable receipt without changing visible data',()=>{const p=add(project(),[person('p1')]);const transfer=packet([person('p1')],1,'new-transfer');const next=M.apply(p,transfer,{});assert.deepEqual(next.people,p.people);assert.deepEqual(next.mach.applied['new-transfer'].pendingIds,[]);assert.equal(next.mach.applied['new-transfer'].payloadFingerprint,JSON.stringify(transfer));});
test('corrupt nested snapshots and executable stored markup reject before restore',()=>{const p=printed(add(project(),[person('p1')]));const corrupt=M.clone(p);corrupt.mach.printJobs[0].entries[0].render=null;assert.throws(()=>M.validateProject(corrupt),/확인본/);const injected=M.clone(p);injected.mach.printJobs[0].entries[0].html='<img src=x onerror=alert(1)>';assert.throws(()=>M.validateProject(injected),/안전/);});

test('durable duplicate receipt rejects changed payload with the same transfer ID',()=>{const p=add(project(),[person('p1')]);const restored=JSON.parse(JSON.stringify(p));assert.throws(()=>M.apply(restored,packet([{...person('p1'),name:'변조'}],1),{p1:{selected:true}}),/전달 번호/);});

test('safe existing SVG logos survive save and restore while executable/network SVG rejects',()=>{const p=project();const svg=source=>'data:image/svg+xml;base64,'+Buffer.from(source).toString('base64');p.customLogos=[{id:'custom-svg',name:'가상 원본 로고',dataUrl:svg('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><defs><path id="shape" d="M0 0h10v10z"/></defs><use href="#shape" fill="#07518a"/></svg>')}];assert.equal(M.validateProject(JSON.parse(JSON.stringify(p))),true);for(const content of ['<svg onload="alert(1)"></svg>','<svg><image href="https://outside.invalid/x"/></svg>','<svg><script>alert(1)</script></svg>','<svg><foreignObject/></svg>']){const bad=M.clone(p);bad.customLogos[0].dataUrl=svg(content);assert.throws(()=>M.validateProject(bad),/SVG/);}});

test('print evidence preserves old source fingerprint independently from current received baseline',()=>{let p=add(project(),[person('p1')]);const initial=Mach.personFingerprint(p.mach.baselines.p1);const job=M.createJob(p,[{participantId:'p1',render:render(p,'p1'),sourceFingerprint:initial}],'frozen-source','2026-01-01');p.mach.printJobs.push(job);p=add(p,[{...person('p1'),position:'새 직책'}],2);p=M.complete(p,'frozen-source','2026-01-03');assert.equal(p.mach.confirmed.p1.sourceFingerprint,initial);assert.notEqual(Mach.personFingerprint(p.mach.baselines.p1),initial);assert.equal(M.status(p,p.people[0],render(p,'p1')),'수정 재출력 필요');});

test('normalized whitespace acknowledgment updates source evidence without rewriting local display',()=>{const p=add(project(),[person('p1')]);const nextPerson={...person('p1'),organization:' 가상   기관 '};const transfer=packet([nextPerson],2);assert.equal(M.review(p,transfer).length,0);const next=M.apply(p,transfer,{});assert.equal(next.people[0].organization,'가상 기관');assert.equal(next.mach.baselines.p1.organization,' 가상   기관 ');});
